<a href="https://colab.research.google.com/github/zaedulislam/The_Python_Mega_Course_Build_10_Real_World_Applications/blob/main/Section%2014%20-%20Numerical%20and%20Scientific%20Computing%20with%20Python%20and%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**numpy** is a base library of **pandas** and **OpenCV** (library for Image Processing)

# 110. Installing OpenCV

In [120]:
import cv2
import numpy as np

# 111. Convert Images to Numpy Arrays

### Reading as Gray scale

In [121]:
imageGray = cv2.imread("/content/drive/MyDrive/Colab Notebooks/The Python Mega Course 2022: Build 10 Real-World Programs/smallgray.png", 0)
imageGray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

### Reading as BGR (RGB)
imageBGR gives transpose matrix of the image

In [122]:
imageBGR = cv2.imread("/content/drive/MyDrive/Colab Notebooks/The Python Mega Course 2022: Build 10 Real-World Programs/smallgray.png", 1)
imageBGR

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

## Convert Numpy Arrays to Images 

In [123]:
cv2.imwrite("newsmallgray.png", imageGray)

True

# 112. Indexing, Slicing, and Iterating Numpy Arrays

In [124]:
imageGray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [125]:
imageGray[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [126]:
imageGray[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [127]:
imageGray[2][4]

182

In [128]:
imageGray[2, 4]

182

In [129]:
imageGray[:, 2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [130]:
for row in imageGray:
    print(row)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


### Transpose of the numpy array

In [131]:
for row in imageGray.T:
    print(row)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [132]:
for value in imageGray.flat:
    print(value)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


# 113. Stacking and Splitting Numpy Arrays

## Stacking Numpy Arrays

To concatenate, each numpy array must be of same dimnesions.

In [133]:
horizontallyStackedImage = np.hstack((imageGray, imageGray))
horizontallyStackedImage

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [134]:
horizontallyStackedImage2 = np.hstack((imageGray, imageGray, imageGray))
print(horizontallyStackedImage2)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [135]:
horizontallyStackedImage3 = np.hstack((imageGray, imageGray))
horizontallyStackedImage3

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [136]:
verticallyStackedImage = np.vstack((imageGray, imageGray))
print(verticallyStackedImage)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


## Splitting Numpy Arrays

In [137]:
horizontallySplitted = np.hsplit(horizontallyStackedImage, 2)
print(horizontallySplitted)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


In [142]:
verticallySplitted = np.vsplit(verticallyStackedImage, 3)
print(verticallySplitted)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8), array([[209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143]], dtype=uint8), array([[198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


In [139]:
type(verticallySplitted)

list

In [140]:
verticallySplitted[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

# Installing OpenCV


<div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="article-asset--content--1dAQ9 rich-text-viewer--rich-text-viewer--19N-I"><p>We will use the OpenCV image processing&nbsp;library. Let us first make sure you have installed the OpenCV&nbsp;library. OpenCV is also referred to as <code>cv2</code> in Python.</p><p><br></p><h4><strong>How to Install OpenCV</strong></h4><p>To install OpenCV for Python 3.9 on Mac or Linux, execute the following in the terminal:</p><p><code>python3.9 -m pip install opencv-python</code></p><p>To install OpenCV for Python 3.9 on Windows, execute the following in the terminal:</p><p><code>py -3.9 -m pip install opencv-python</code></p><p><strong>Note:&nbsp;The above commands work for Python 3.9. You may need to replace the </strong><code><strong>3.9</strong></code><strong> part from the commands with the number of the Python version you are using in your system. For example, you may need to type </strong><code>python3.10</code><strong> instead of </strong><code>python3.9.</code></p><p>Once the installation completes, open a Python session and try:</p><p><code>import cv2</code>&nbsp;</p><p>If you get no errors, you installed OpenCV successfully. If you get an error, see the FAQs below:</p><p><br></p><p><strong>FAQs</strong></p><p><strong>1. My OpenCV installation didn't work on Windows</strong></p><p>Solution: </p><p>1. Uninstall OpenCV with:</p><p><code>py -3.9 -m pip uninstall opencv-python</code></p><p>2. Download a wheel (.whl) file from <a target="_blank" rel="noopener noreferrer" href="http://www.lfd.uci.edu/~gohlke/pythonlibs/#opencv">this link</a> and install the file with pip. Make sure you download&nbsp;the correct file for your Windows and your Python versions. For example, for&nbsp;Python 3.6 on&nbsp;Windows 64-bit, you would do this:</p><p><code>py -3.9 -m pip install opencv_python‑3.2.0‑cp39‑cp39m‑win_amd64.whl</code>&nbsp;</p><p>3. Try to import cv2 in Python again. If there's still an error, type the following again in the command line:</p><p><code>py -3.9 -m pip install opencv-python</code>&nbsp;<br>4. Try importing cv2 again. It should work at this point.<strong> </strong></p><p><br></p><p><strong>2. My OpenCV installation didn't work on Mac</strong></p><p>Solution:</p><p>If <code>python3.9 -m pip install opencv-python</code> here are alternative steps to install OpenCV:</p><p>1. Install <em>brew</em>.</p><p>To install <em>brew, </em>open your terminal, and execute the following:</p><p><code>/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"</code></p><p>2. OpenCV depends on GTK+, so install that dependency&nbsp;first with brew (always from the terminal):<br></p><p><code>brew install gtk+</code>&nbsp;<br></p><p>3. Install OpenCV with brew:</p><p><code>brew install opencv</code>&nbsp;<br></p><p>4. Open Python and try to import OpenCV with:</p><p><code>import cv2</code>&nbsp;<br></p><p>If you get no errors, you installed OpenCV successfully.</p><p><br></p><p><strong>3. My OpenCV installation didn't work on Linux</strong></p><p>1. Open your terminal and execute the following commands, one by one:</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">sudo apt</span><span class="pun">-</span><span class="kwd">get</span><span class="pln"> install libqt4</span><span class="pun">-</span><span class="pln">dev</span></li><li class="L1"><span class="pln">cmake </span><span class="pun">-</span><span class="pln">D WITH_QT</span><span class="pun">=</span><span class="pln">ON </span><span class="pun">..</span></li><li class="L2"><span class="pln">make</span></li><li class="L3"><span class="pln">sudo make install</span></li></ol></pre></div></div><p>2.&nbsp;2.&nbsp;If the above commands don't work, execute this:</p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">sudo apt</span><span class="pun">-</span><span class="kwd">get</span><span class="pln"> install libopencv</span><span class="pun">-*</span></li></ol></pre></div></div><p>3.&nbsp;Then, install OpenCV with pip:</p><p><code>python3.9 -m pip install opencv-python</code>&nbsp;<br></p><p>4. Import cv2 in Python.&nbsp;If you get no errors, you installed OpenCV successfully.</p></div>